"""Create Database

Revision ID: 71ad7420fd66
Revises: 
Create Date: 2023-07-03 21:59:26.028573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71ad7420fd66'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Column('uuid', sa.String, primary_key=True)
    sa.Column('text', sa.String, nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
