"""Create database

Revision ID: c6db5a67a869
Revises: 
Create Date: 2023-07-03 09:24:13.928556

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c6db5a67a869'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create the Entry table
    op.create_table(
        'Entry',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('uuid', sa.String(36), nullable=False),
        sa.Column('text', sa.String(255), nullable=True),
        sa.UniqueConstraint('uuid', name='ux_Entry_uuid')

    )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
